### ISSUE TITLE
Incorrect output: equal section is included in the conflict.

### ISSUE THREAD

**Issue by rdev1983** [nasdf/diff3#1]
\#\#\# O:
Aa
Bb
Cc
\#\#\# A:
Aa
Bb
Cc
Dd
Ee
Ff
\#\#\# B:
Aa
Bb
=======================================================
For above case diff3 produces following output
Aa
Bb
\<\<\<\<\<\<\<
Cc
Dd
Ee
Ff
\=\=\=\=\=\=\=
\>\>\>\>\>\>\>

But this code is producing following output
\<\<\<\<\<\<\<
Aa
Bb
Cc
Dd
Ee
Ff
\=\=\=\=\=\=\=
Aa
Bb
\>\>\>\>\>\>\>

Aa and Bb is common in two side of the conflict so shouldn't it be moved out of conflict?

**Comment by nasdf** [comment]
Thanks for reporting this! It should be fixed in the latest release.
